import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import QueryProvider from "../components/query-provider";
import { Toaster } from "../components/ui/sonner";
import { cn } from "@/lib/utils";
import { NuqsAdapter } from "nuqs/adapters/next/app";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jira clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, "antialiased min-h-screen")}
      >
        <QueryProvider>
          <Toaster />
          <NuqsAdapter>
            {children}
          </NuqsAdapter>
        </QueryProvider>
      </body>
    </html>
  );
}